# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Python/pip updates
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"

  # GitHub Actions updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      codeql:
        patterns:
          - "github/codeql-action*"
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"

  # JavaScript/npm updates
  - package-ecosystem: npm
    directories:
      - /javascript
      - /demo
    schedule:
      interval: weekly
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"

  # Java/Maven updates
  - package-ecosystem: maven
    directory: /java
    schedule:
      interval: weekly
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"
