name: Unittest for JavaScript
on:
  push:
    paths:
      - 'javascript/**'
  pull_request:
    paths:
      - 'javascript/**'
permissions:
  contents: read

jobs:
  javascript-unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20, 22, 24]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
        working-directory: ./javascript
      - name: Create symlink
        run: npm link
        working-directory: ./javascript
      - name: Build package
        run: npm run build --if-present
        working-directory: ./javascript
      - name: Run testcases
        run: npm test
        working-directory: ./javascript
