# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Train Japanese Model (KNBC)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  train:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install ".[jaxcpu]"
      - name: Prepare KNBC data
        run: |
          curl -o knbc.tar.bz2 https://nlp.ist.i.kyoto-u.ac.jp/kuntt/KNBC_v1.0_090925_utf8.tar.bz2
          tar -xf knbc.tar.bz2
          python scripts/prepare_knbc.py KNBC_v1.0_090925_utf8 -o source_knbc.txt
      - name: Encode data
        run: python scripts/encode_data.py source_knbc.txt -o encoded_knbc.txt
      - name: Train model
        run: |
          echo "Starting training..."
          start_time=$(date +%s)
          python scripts/train.py encoded_knbc.txt -o weights_knbc.txt --iter 100000
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "Training finished."
          echo "Duration: $duration seconds"
          echo "Duration: $(($duration / 60)) minutes and $(($duration % 60)) seconds"
      - name: Build model
        run: python scripts/build_model.py weights_knbc.txt -o model.json
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: budoux-ja-knbc-model
          path: model.json
